version: '3'
services:
  activemq:
    container_name: activemq
    image: codingpuss/activemq:5.17.2-jre-19-alpine
    ports:
      - 8161:8161
      - 61616:61616
      -
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql-root-password
      POSTGRES_DB: VKR
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"